"""Render the four dashboard pages from results/ and data/.

Each page has one builder taking the results directory and returning the
full HTML string. `PAGES` maps output filenames to builders; the snapshot
loop's HTTP handler resolves request paths through `resolve_page` and
renders on demand, while `python -m fifa_fantasy.web` writes the same
pages as static files so everything also works over file://.

Data discipline. Anything cheap enough to read per request (recommendation
JSONs, recent signal parquets) is read live so a browser refresh reflects
the newest run. Anything heavy (calibration parquets, market history,
matplotlib) is consumed via results/report/report_data.json and the
pre-rendered SVGs in results/figures/, both regenerated by the tick's
`python -m fifa_fantasy.report` step.
"""

from __future__ import annotations

import json
import math
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from jinja2 import Environment, FileSystemLoader, select_autoescape
from markupsafe import Markup

from fifa_fantasy.report import data as report_data
from fifa_fantasy.report.data import (
    STAGE_LABEL,
    aggregate_signals,
    latest_recommendation_per_backend,
    list_recommendations,
    load_signals,
    official_backend,
    official_recommendation,
    signals_for_squad,
)
from fifa_fantasy.report.figures import BACKEND_LABELS
from fifa_fantasy.report.registry import (
    GENERATIONS,
    MODEL_REGISTRY,
    NEGATIVE_RESULTS,
    TIMELINE,
)

ROOT = Path(__file__).resolve().parent
TEMPLATES_DIR = ROOT / "templates"

# Pitch is drawn top (attack) to bottom (keeper).
LINE_ORDER = ["FWD", "MID", "DEF", "GK"]

SIGNAL_WINDOW_DAYS = 3.0

# The intelligence table is capped after triage sorting; the full corpus
# stays in the parquet snapshots. Half a megabyte of table rows helps
# nobody make a decision.
SIGNAL_TABLE_CAP = 400
_EVIDENCE_CHARS = 240

# Freshness sources: label, newest-of glob (relative to the project root),
# and the cadence (hours) the loop refreshes them on. Age past 1.5x the
# cadence is a warning, past 3x is stale.
FRESHNESS_SOURCES = [
    ("Squad + fixtures", "data/raw/players_*.parquet", 12.0),
    ("GBM retrain", "data/models/gbm_FWD_mean.txt", 12.0),
    ("Report + figures", "results/report/report_data.json", 12.0),
    ("Prediction markets", "data/external/prediction_markets/*.jsonl", 3.0),
    ("News feed", "data/external/news_articles/*.parquet", 6.0),
    ("News signals", "data/external/player_signals/*.parquet", 6.0),
    ("Elo ratings", "data/external/country_elo.csv", 24.0),
]


def _clean(value):
    """NaN and None both render as a blank; everything else passes through."""
    if value is None:
        return None
    if isinstance(value, float) and math.isnan(value):
        return None
    return value


def _group_by_stage(items: list[dict]) -> list[dict]:
    """Return {stage, items} groups in canonical round order, newest first."""
    by_stage: dict[str, list[dict]] = {}
    for item in items:
        stage = item.get("stage") or "UNKNOWN"
        by_stage.setdefault(stage, []).append(item)

    groups = []
    for stage in sorted(by_stage.keys(),
                        key=lambda s: report_data.STAGE_ORDER.get(s, 99)):
        ordered = sorted(by_stage[stage],
                         key=lambda x: x.get("generated_at_utc", ""),
                         reverse=True)
        groups.append({
            "stage": stage,
            "stage_label": STAGE_LABEL.get(stage, stage),
            "items": ordered,
        })
    return groups


def _augment_featured(rec: dict) -> dict:
    """Split the squad into pitch lines, bench, captain and vice for display."""
    squad = rec.get("squad", [])
    lines = {"GK": [], "DEF": [], "MID": [], "FWD": []}
    bench = []
    captain = vice = None
    for p in squad:
        p = dict(p)
        p["display_name"] = _clean(p.get("known_name")) or p.get("full_name")
        p["predicted_q10"] = _clean(p.get("predicted_q10"))
        p["predicted_q90"] = _clean(p.get("predicted_q90"))
        p["form"] = _clean(p.get("form"))
        if p.get("role") == "Captain":
            captain = p
        elif p.get("role") == "Vice":
            vice = p
        if p.get("in_starting_xi"):
            lines.setdefault(p.get("position", "?"), []).append(p)
        else:
            bench.append(p)

    def ceiling(p):
        return p.get("predicted_q90") or p.get("predicted_points", 0.0)

    for pos in lines:
        lines[pos].sort(key=ceiling, reverse=True)
    bench.sort(key=lambda p: p.get("bench_priority", 99))

    starters_flat = []
    for pos in ["GK", "DEF", "MID", "FWD"]:
        starters_flat.extend(lines[pos])

    return {
        "pitch_lines": [(pos, lines.get(pos, [])) for pos in LINE_ORDER],
        "starters": starters_flat,
        "bench": bench,
        "captain": captain,
        "vice": vice,
    }


def _relative_age(seconds: float) -> str:
    if seconds < 90:
        return f"{int(seconds)}s ago"
    minutes = seconds / 60
    if minutes < 90:
        return f"{int(minutes)}m ago"
    hours = minutes / 60
    if hours < 36:
        return f"{hours:.1f}h ago"
    return f"{hours / 24:.1f}d ago"


def _freshness(root: Path, now: datetime) -> list[dict]:
    out = []
    for label, pattern, cadence_h in FRESHNESS_SOURCES:
        matches = list(root.glob(pattern))
        if not matches:
            out.append({"label": label, "status": "missing",
                        "age_str": "no data", "when": ""})
            continue
        newest = max(matches, key=lambda p: p.stat().st_mtime)
        mtime = datetime.fromtimestamp(newest.stat().st_mtime, tz=timezone.utc)
        age_s = (now - mtime).total_seconds()
        age_h = age_s / 3600
        if age_h <= cadence_h * 1.5:
            status = "fresh"
        elif age_h <= cadence_h * 3:
            status = "warn"
        else:
            status = "stale"
        out.append({
            "label": label,
            "status": status,
            "age_str": _relative_age(age_s),
            "when": mtime.strftime("%Y-%m-%d %H:%M UTC"),
        })
    return out


def _env() -> Environment:
    return Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=select_autoescape(["html"]),
    )


def _load_report_bundle(results_dir: Path) -> dict:
    path = results_dir / "report" / "report_data.json"
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return {}


def _inline_svg(results_dir: Path, name: str) -> Markup | None:
    """Read a pre-rendered figure and return its <svg> element inline."""
    path = results_dir / "figures" / f"{name}.svg"
    try:
        text = path.read_text()
    except OSError:
        return None
    start = text.find("<svg")
    if start == -1:
        return None
    return Markup(text[start:])


def _figs(results_dir: Path, names: list[str]) -> dict[str, Markup]:
    out = {}
    for name in names:
        svg = _inline_svg(results_dir, name)
        if svg is not None:
            out[name] = svg
    return out


def _signal_rows(frame: pd.DataFrame, now: datetime) -> list[dict]:
    """Aggregated signal frame to template-friendly dicts with an age."""
    rows = []
    if frame is None or frame.empty:
        return rows
    for r in frame.itertuples():
        published = pd.to_datetime(r.published_at_utc, errors="coerce",
                                   utc=True)
        age = ""
        if published is not None and not pd.isna(published):
            age = _relative_age((now - published.to_pydatetime()).total_seconds())
        evidence = str(r.evidence or "")
        if len(evidence) > _EVIDENCE_CHARS:
            evidence = evidence[:_EVIDENCE_CHARS - 1].rstrip() + "…"
        rows.append({
            "player_id": int(r.player_id),
            "full_name": r.full_name,
            "country_abbr": r.country_abbr,
            "position": r.position,
            "signal": r.signal,
            "signal_class": r.signal_class,
            "mentions": int(getattr(r, "mentions", 1)),
            "evidence": evidence,
            "source_id": r.source_id,
            "url": r.url,
            "age_str": age,
        })
    return rows


def _common_context(results_dir: Path, now: datetime, page: str) -> dict:
    recs = list_recommendations(results_dir)
    stages = [r.get("stage") for r in recs
              if r.get("stage") in report_data.STAGE_ORDER]
    stage = (max(stages, key=lambda s: report_data.STAGE_ORDER[s])
             if stages else None)
    return {
        "page": page,
        "built_at": now.strftime("%Y-%m-%d %H:%M:%S UTC"),
        "stage": stage,
        "stage_label": STAGE_LABEL.get(stage, stage) if stage else None,
        "freshness": _freshness(results_dir.parent, now),
    }


def _root_dirs(results_dir: Path) -> dict[str, Path]:
    root = results_dir.parent
    return {
        "root": root,
        "signals": root / "data" / "external" / "player_signals",
        "processed": root / "data" / "processed",
    }


# ---------------------------------------------------------------------------
# Page builders
# ---------------------------------------------------------------------------

def build_overview(results_dir: Path) -> str:
    now = datetime.now(timezone.utc)
    ctx = _common_context(results_dir, now, "overview")
    dirs = _root_dirs(results_dir)

    official, fallback = official_recommendation(results_dir)
    featured_extra = _augment_featured(official) if official else None

    per_backend = latest_recommendation_per_backend(results_dir)
    agreement = {"agree": "-", "n_backends": len(per_backend)}
    if official:
        own = set(official.get("squad_player_ids", []))
        others = [r for r in per_backend.values()
                  if r.get("__filename__") != official.get("__filename__")]
        if own and others:
            overlaps = [len(own & set(r.get("squad_player_ids", [])))
                        for r in others]
            agreement = {"agree": round(sum(overlaps) / len(overlaps)),
                         "n_backends": len(others) + 1}

    squad_signals: list[dict] = []
    squad_signals_total = 0
    if official:
        signals = load_signals(dirs["signals"], days=SIGNAL_WINDOW_DAYS)
        if not signals.empty:
            agg = aggregate_signals(signals)
            squad = signals_for_squad(agg,
                                      official.get("squad_player_ids", []))
            squad_signals_total = int(len(squad))
            # The overview is a decision page; the top of the triage order
            # belongs here and the full list lives on the intelligence page.
            squad_signals = _signal_rows(squad.head(20), now)

    history = []
    for group in _group_by_stage(list_recommendations(results_dir)):
        items = [r for r in group["items"]
                 if not official
                 or r.get("__filename__") != official.get("__filename__")]
        if items:
            history.append({**group, "items": items})
    history.reverse()

    bundle = _load_report_bundle(results_dir)
    return _env().get_template("overview.html.jinja").render(
        **ctx,
        official=official,
        official_is_fallback=fallback,
        official_backend=official_backend(),
        f=featured_extra,
        agreement=agreement,
        squad_signals=squad_signals,
        squad_signals_total=squad_signals_total,
        signal_days=int(SIGNAL_WINDOW_DAYS),
        history=history,
        final_plan=bundle.get("final_plan"),
        match_forecast=bundle.get("match_forecast"),
        figs=_figs(results_dir, ["fig_final_probs"]),
    )


def build_algorithms(results_dir: Path) -> str:
    now = datetime.now(timezone.utc)
    ctx = _common_context(results_dir, now, "algorithms")
    bundle = _load_report_bundle(results_dir)

    per_backend = latest_recommendation_per_backend(results_dir)
    backtest = bundle.get("backtest")

    tabs = []
    for record in MODEL_REGISTRY:
        rec = per_backend.get(record.key)
        row = None
        total = None
        if backtest and record.key in backtest.get("series", {}):
            row = backtest["series"][record.key]
            total = backtest["cumulative"][record.key][-1]
        tabs.append({
            "record": record,
            "rec": rec,
            "f": _augment_featured(rec) if rec else None,
            "formula_svg": _inline_svg(results_dir, f"formula_{record.key}"),
            "backtest_row": row,
            "backtest_total": total,
        })

    return _env().get_template("algorithms.html.jinja").render(
        **ctx,
        tabs=tabs,
        validation=bundle.get("validation") or [],
        routing=bundle.get("routing") or {},
        backtest=backtest,
    )


def build_intelligence(results_dir: Path) -> str:
    now = datetime.now(timezone.utc)
    ctx = _common_context(results_dir, now, "intelligence")
    dirs = _root_dirs(results_dir)
    bundle = _load_report_bundle(results_dir)

    signals = load_signals(dirs["signals"], days=SIGNAL_WINDOW_DAYS)
    agg = aggregate_signals(signals) if not signals.empty else pd.DataFrame()

    official, _ = official_recommendation(results_dir)
    squad_signals: list[dict] = []
    if official and not agg.empty:
        squad_signals = _signal_rows(
            signals_for_squad(agg, official.get("squad_player_ids", [])), now)

    coverage = bundle.get("signals_coverage") or {
        "articles_cached": 0, "signal_rows": int(len(signals)),
        "players_flagged": 0, "by_class": {}, "by_signal": {}}
    # Live corpus numbers where cheap; the bundle fills the rest.
    coverage = dict(coverage)
    coverage["signal_rows"] = int(len(signals))
    if not signals.empty:
        coverage["players_flagged"] = int(signals["player_id"].nunique())

    players_indexed = "-"
    pred_files = sorted(dirs["processed"].glob("predictions_*.parquet"))
    if pred_files:
        try:
            import pyarrow.parquet as pq
            col = pq.read_table(pred_files[-1], columns=["player_id"])
            players_indexed = f"{col['player_id'].to_pandas().nunique():d}"
        except Exception:
            players_indexed = "-"

    total_findings = int(len(agg)) if not agg.empty else 0
    if total_findings > SIGNAL_TABLE_CAP:
        agg = agg.head(SIGNAL_TABLE_CAP)

    return _env().get_template("intelligence.html.jinja").render(
        **ctx,
        signals=_signal_rows(agg, now),
        total_findings=total_findings,
        table_cap=SIGNAL_TABLE_CAP,
        squad_signals=squad_signals,
        coverage=coverage,
        players_indexed=players_indexed,
        signal_days=int(SIGNAL_WINDOW_DAYS),
        market_latest=bundle.get("market_latest") or [],
        figs=_figs(results_dir, ["fig_signal_volume", "fig_market_odds"]),
    )


def build_research(results_dir: Path) -> str:
    now = datetime.now(timezone.utc)
    ctx = _common_context(results_dir, now, "research")
    bundle = _load_report_bundle(results_dir)

    return _env().get_template("research.html.jinja").render(
        **ctx,
        timeline=TIMELINE,
        generations=GENERATIONS,
        negative_results=NEGATIVE_RESULTS,
        backtest=bundle.get("backtest"),
        backend_labels=BACKEND_LABELS,
        walkforward=bundle.get("walkforward"),
        calibration_summary=bundle.get("calibration_summary") or [],
        match_forecast=bundle.get("match_forecast"),
        figs=_figs(results_dir, [
            "fig_backtest_cumulative", "fig_backtest_rounds",
            "fig_holdout_rmse", "fig_walkforward", "fig_calibration",
            "fig_gk_sweep", "fig_market_negative", "fig_forecast_skill",
        ]),
    )


PAGES = {
    "index.html": build_overview,
    "algorithms.html": build_algorithms,
    "intelligence.html": build_intelligence,
    "research.html": build_research,
}


def resolve_page(path: str) -> str | None:
    """Map a request path to a page filename, or None for static paths."""
    name = path.split("?", 1)[0].split("#", 1)[0].lstrip("/")
    if not name:
        name = "index.html"
    if not name.endswith(".html"):
        name = f"{name}.html"
    return name if name in PAGES else None


def build_all(results_dir: Path) -> dict[str, str]:
    """Render every page; used by the static writer."""
    return {name: builder(results_dir) for name, builder in PAGES.items()}
