"""Render a recommendation as a human-readable markdown report.

Pure formatting. Inputs are the same objects the CLI already has after
running the squad + lineup solvers, so this is just presentation.
"""

from __future__ import annotations

from typing import Any

import pandas as pd

from .solvers import TransferSolution

POSITION_ORDER = {"GK": 0, "DEF": 1, "MID": 2, "FWD": 3}


def _format_table(rows: list[dict[str, Any]], cols: list[str]) -> str:
    header = "| " + " | ".join(cols) + " |"
    sep = "|" + "|".join(["---"] * len(cols)) + "|"
    lines = [header, sep]
    for r in rows:
        lines.append("| " + " | ".join(str(r[c]) for c in cols) + " |")
    return "\n".join(lines)


def render_markdown(
    *,
    stage: str,
    horizon_rounds: list[int],
    budget_used: float,
    budget_total: float,
    total_horizon_points: float,
    formation: str,
    xi_expected_points: float,
    squad_player_ids: list[int],
    starter_ids: list[int],
    bench_ids_priority_order: list[int],
    captain_id: int,
    vice_captain_id: int,
    players: pd.DataFrame,
    round_predictions: pd.DataFrame,
    target_round: int,
    transfer: TransferSolution | None = None,
) -> str:
    """Return a markdown report string.

    `players` must be indexed by player_id (or contain that as a column).
    `round_predictions` contains predicted_points + matchup context for
    `target_round` for every player_id in the squad.
    """
    if "player_id" in players.columns and players.index.name != "player_id":
        players = players.set_index("player_id")
    round_idx = round_predictions.set_index("player_id")

    starter_set = set(starter_ids)
    bench_pos = {pid: i + 1 for i, pid in enumerate(bench_ids_priority_order)}

    def role(pid: int) -> str:
        if pid == captain_id:
            return "Captain (C)"
        if pid == vice_captain_id:
            return "Vice (V)"
        if pid in starter_set:
            return "Start"
        return f"Bench {bench_pos[pid]}"

    rows = []
    for pid in squad_player_ids:
        p = players.loc[pid]
        r = round_idx.loc[pid]
        rows.append({
            "_pos_sort": POSITION_ORDER[p["position"]],
            "_md_pred": float(r["predicted_points"]),
            "Role": role(pid),
            "Player": p["full_name"],
            "Cty": p["country_abbr"],
            "Pos": p["position"],
            "Price": f"${float(p['price_millions']):.1f}M",
            "Own%": f"{float(p['ownership_fraction']) * 100:.1f}%",
            "Opp": ("vs " if bool(r["is_home"]) else "@ ") + str(r["opponent_abbr"]),
            f"R{target_round} E[pts]": f"{float(r['predicted_points']):.2f}",
        })
    rows.sort(key=lambda x: (x["_pos_sort"], -x["_md_pred"]))
    table = _format_table(
        rows,
        ["Role", "Player", "Cty", "Pos", "Price", "Own%", "Opp",
         f"R{target_round} E[pts]"],
    )

    captain_pred = float(round_idx.loc[captain_id, "predicted_points"])
    vice_pred = float(round_idx.loc[vice_captain_id, "predicted_points"])
    captain_row = players.loc[captain_id]
    vice_row = players.loc[vice_captain_id]

    bench_lines = []
    for pos, pid in enumerate(bench_ids_priority_order, start=1):
        p = players.loc[pid]
        suffix = ""
        if p["position"] == "GK":
            suffix = " — only subs in if starting GK plays 0 minutes"
        bench_lines.append(
            f"{pos}. **{p['full_name']}** ({p['country_abbr']}, {p['position']}){suffix}"
        )

    transfer_section = ""
    if transfer is not None and (transfer.transfers_in or transfer.transfers_out):
        out_lines = [
            f"- **{players.loc[pid, 'full_name']}** "
            f"({players.loc[pid, 'country_abbr']}, {players.loc[pid, 'position']}, "
            f"${float(players.loc[pid, 'price_millions']):.1f}M)"
            for pid in transfer.transfers_out
        ]
        in_lines = [
            f"- **{players.loc[pid, 'full_name']}** "
            f"({players.loc[pid, 'country_abbr']}, {players.loc[pid, 'position']}, "
            f"${float(players.loc[pid, 'price_millions']):.1f}M)"
            for pid in transfer.transfers_in
        ]
        hit_line = (
            f"- **{transfer.n_transfers} transfers**, "
            f"{transfer.n_extra_transfers} above quota → "
            f"**−{transfer.transfer_cost_points} pt hit**, "
            f"net horizon expected **{transfer.objective:.2f}**."
        )
        transfer_section = (
            "\n## Transfers from previous squad\n\n"
            "### OUT\n\n" + ("\n".join(out_lines) or "(none)") + "\n\n"
            "### IN\n\n" + ("\n".join(in_lines) or "(none)") + "\n\n"
            + hit_line + "\n"
        )

    md = f"""# Recommendation — {stage}

Generated by `python -m fifa_fantasy.optimizer`. Predictor: current model
output in `data/processed/predictions_*.parquet`.

## Headline

- **Stage**: {stage}
- **Horizon optimized**: rounds {horizon_rounds}
- **Budget**: ${budget_used:.1f}M of ${budget_total:.1f}M used
- **Formation**: {formation}
- **R{target_round} starting-XI expected**: {xi_expected_points:.2f} pts
- **R{target_round} with captain doubling**: {xi_expected_points + captain_pred:.2f} pts
- **Total horizon expected**: {total_horizon_points:.2f} pts

## Squad of 15

{table}

## Captain

- Captain: **{captain_row['full_name']}** ({captain_row['country_abbr']},
  ${float(captain_row['price_millions']):.1f}M), E[pts]={captain_pred:.2f}
  → doubled to **{2 * captain_pred:.2f}**.
- Vice-captain: **{vice_row['full_name']}** ({vice_row['country_abbr']}),
  E[pts]={vice_pred:.2f}. Activates only if the captain plays 0 minutes
  AND no manual changes are made during the round.

## Bench (auto-sub priority)

""" + "\n".join(bench_lines) + "\n" + transfer_section

    return md
