"""Emit LaTeX table fragments and number macros for the paper.

Reads the same evaluation artifacts the dashboard uses (via
fifa_fantasy.report.data loaders) and writes booktabs fragments plus a
numbers.tex macro file into paper/generated/. The paper \\input{}s these
fragments so no computed number is ever hand-copied into prose.

    python scripts/paper_tables.py --out paper/generated
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from fifa_fantasy.report.data import (  # noqa: E402
    STAGE_LABEL,
    load_backtest,
    load_gk_sweep,
    load_market_negative,
    load_validation_report,
    load_walkforward,
)

HEADER = "% GENERATED by scripts/paper_tables.py -- do not edit\n"

# TeX control words are letters-only; spell out any digit.
_DIGITS = str.maketrans({"0": "Zero", "1": "One", "2": "Two", "3": "Three",
                         "4": "Four", "5": "Five", "6": "Six",
                         "7": "Seven", "8": "Eight", "9": "Nine"})


def _macro_name(name: str) -> str:
    return name.translate(_DIGITS)
BACKEND_LABEL = {
    "heuristic": "Heuristic",
    "heuristic_v2": "Heuristic v2",
    "poisson": "Poisson",
    "gbm": "GBM",
    "monte_carlo": "Monte Carlo",
    "ensemble": "Ensemble",
    "user_actual": "User (actual)",
    "random_baseline": "Random baseline",
}
CONFIG_LABEL = {
    "A_epl_noform": "A: EPL, no form",
    "B_epl_form": "B: EPL + form",
    "C_eplwc_form": "C: EPL+WC + form",
    "D_eplwc_all": "D: EPL+WC, proxy minutes",
    "E_eplwc_xg": "E: EPL+WC, real xG form",
    "F_eplwc_minutes": "F: EPL+WC, real minutes",
}

# Primary-record numbers computed once during the tournament and documented
# with their own provenance; they are not regenerable from the shipped
# artifacts (the archived pre-R16 feature snapshots predate the columns
# involved). Sources: docs/whitepaper/sections/11g (participation buckets,
# availability A/B, captain-rule backtest, variance stds and correlations),
# pytest --collect-only on 2026-07-18 (test count), players_2026-07-11
# truncation audit, and the 2026-06-29 market snapshot vs country Elo
# (log-price correlation, n=27 priced countries).
HISTORICAL_MACROS: list[tuple[str, str]] = [
    ("TestCount", "352"),
    ("TruncationShareQf", "49\\%"),
    ("MarketEloCorr", "0.89"),
    ("GlobalRankSF", "1{,}153{,}720"),
    ("PartLowMean", "1.67"), ("PartLowBlank", "36\\%"), ("PartLowN", "613"),
    ("PartMidMean", "2.50"), ("PartMidBlank", "19\\%"),
    ("PartHighMean", "3.07"), ("PartHighBlank", "13\\%"),
    ("PartHighN", "1{,}526"), ("PartStartCorr", "0.171"),
    ("AvailabilityWithout", "275"), ("AvailabilityWith", "283"),
    ("CaptainMeanPts", "11"), ("CaptainBlendPts", "15"),
    ("CaptainCeilingPts", "21"), ("CaptainOraclePts", "42"),
    ("RoundStdPredicted", "5.8"), ("RoundStdRealized", "19.4"),
    ("CorrFixtureGap", "0.48"), ("CorrModelPrediction", "0.67"),
]
ALL_STAGES = ["GROUP_MD1", "GROUP_MD2", "GROUP_MD3",
              "R32", "R16", "QF", "SF", "FINAL"]


def _f(x: float, nd: int = 3) -> str:
    return f"{x:.{nd}f}"


def _write(out_dir: Path, name: str, body: str) -> None:
    path = out_dir / name
    path.write_text(HEADER + body)
    print(f"wrote {path}")


def tab_holdout_rmse(out_dir: Path) -> list[tuple[str, str]]:
    rows = load_validation_report(ROOT / "data/training")
    lines = [r"\begin{tabular}{lrrrr}", r"\toprule",
             r"Position & $n$ & Heuristic & Poisson & GBM \\", r"\midrule"]
    macros: list[tuple[str, str]] = []
    for r in rows:
        vals = {"heuristic": r["heuristic_rmse"], "poisson": r["poisson_rmse"],
                "gbm": r["gbm_rmse"]}
        best = min(vals, key=vals.get)
        cells = [(r"\textbf{" + _f(v) + "}") if k == best else _f(v)
                 for k, v in vals.items()]
        lines.append(f"{r['position']} & {r['n']} & "
                     + " & ".join(cells) + r" \\")
        for k, v in vals.items():
            macros.append((f"Rmse{r['position'].title()}{k.title()}", _f(v)))
    lines += [r"\bottomrule", r"\end{tabular}"]
    _write(out_dir, "tab_holdout_rmse.tex", "\n".join(lines) + "\n")
    return macros


def tab_walkforward(out_dir: Path) -> list[tuple[str, str]]:
    wf = load_walkforward(ROOT / "data/evaluation")
    pooled = wf["pooled"]
    cols = ["GK", "DEF", "MID", "FWD", "ALL"]
    best = {c: min(pooled, key=lambda k: pooled[k][c]) for c in cols}
    lines = [r"\begin{tabular}{lrrrrr}", r"\toprule",
             r"Config & GK & DEF & MID & FWD & All \\", r"\midrule"]
    for cfg, vals in pooled.items():
        cells = [(r"\textbf{" + _f(vals[c]) + "}") if best[c] == cfg
                 else _f(vals[c]) for c in cols]
        lines.append(CONFIG_LABEL.get(cfg, cfg) + " & "
                     + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    _write(out_dir, "tab_walkforward.tex", "\n".join(lines) + "\n")
    return [("WalkforwardPooled" + cfg.split("_")[0], _f(vals["ALL"]))
            for cfg, vals in pooled.items()]


def tab_backtest_rounds(out_dir: Path) -> list[tuple[str, str]]:
    bt = load_backtest(ROOT / "data/evaluation")
    order = ["heuristic", "heuristic_v2", "poisson", "gbm",
             "monte_carlo", "ensemble", "user_actual", "random_baseline"]
    present = [b for b in order if b in bt["series"]]
    head = " & ".join(BACKEND_LABEL[b] for b in present)
    lines = [r"\begin{tabular}{l" + "r" * len(present) + "}", r"\toprule",
             f"Round & {head} " + r"\\", r"\midrule"]
    for i, rnd in enumerate(bt["rounds"]):
        cells = [f"{bt['series'][b][i]:.0f}" for b in present]
        lines.append(f"{rnd['stage_label']} & " + " & ".join(cells) + r" \\")
    lines.append(r"\midrule")
    totals = bt["totals"]
    total_map = {**{b: totals.get(b) for b in present},
                 "user_actual": totals.get("user_actual_net"),
                 "random_baseline": totals.get("random_baseline_mean")}
    cells = [f"{total_map[b]:.0f}" if total_map[b] is not None else "--"
             for b in present]
    lines.append(r"\textbf{Cumulative} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    _write(out_dir, "tab_backtest_rounds.tex", "\n".join(lines) + "\n")
    macros = [("Total" + b.title().replace("_", ""), f"{v:.0f}")
              for b, v in totals.items()]
    return macros


def tab_gk_ab(out_dir: Path) -> list[tuple[str, str]]:
    rows = load_gk_sweep(ROOT / "data/evaluation")
    lines = [r"\begin{tabular}{lrrrr}", r"\toprule",
             r"Dataset & $n$ & RMSE v1 & RMSE v2 & $\Delta$RMSE \\",
             r"\midrule"]
    macros: list[tuple[str, str]] = []
    for r in rows:
        lines.append(f"{r['dataset'].replace('_', ' ')} & {r['n']} & "
                     f"{_f(r['rmse_v1'])} & {_f(r['rmse_v2'])} & "
                     f"{_f(r['delta_rmse'])} " + r"\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    _write(out_dir, "tab_gk_ab.tex", "\n".join(lines) + "\n")
    if rows:
        macros.append(("GkRmseVOne", _f(rows[0]["rmse_v1"])))
        macros.append(("GkRmseVTwo", _f(rows[0]["rmse_v2"])))
    return macros


def tab_market_negative(out_dir: Path) -> list[tuple[str, str]]:
    mk = load_market_negative(ROOT / "data/evaluation")
    rows = mk["rows"]
    rounds = sorted({r["round_id"] for r in rows})
    backends = sorted({r["backend"] for r in rows},
                      key=lambda b: list(BACKEND_LABEL).index(b)
                      if b in BACKEND_LABEL else 99)
    by = {(r["backend"], r["round_id"]): r["delta_rmse"] for r in rows}
    head = " & ".join(f"R{r}" for r in rounds)
    lines = [r"\begin{tabular}{l" + "r" * (len(rounds) + 1) + "}",
             r"\toprule",
             f"Backend & {head} & Mean " + r"\\", r"\midrule"]
    deltas_all = []
    for b in backends:
        deltas = [by[(b, r)] for r in rounds if (b, r) in by]
        deltas_all += deltas
        cells = [_f(by[(b, r)]) if (b, r) in by else "--" for r in rounds]
        mean = sum(deltas) / len(deltas) if deltas else float("nan")
        lines.append(f"{BACKEND_LABEL.get(b, b)} & " + " & ".join(cells)
                     + f" & {_f(mean)} " + r"\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    _write(out_dir, "tab_market_negative.tex", "\n".join(lines) + "\n")
    grand = sum(deltas_all) / len(deltas_all)
    return [("MarketMeanDeltaRmse", _f(grand)),
            ("MarketBetaTwo", _f(mk["config"]["beta_2"], 1))]


def tab_season_summary(out_dir: Path) -> list[tuple[str, str]]:
    bt = load_backtest(ROOT / "data/evaluation")
    have = {r["stage"]: i for i, r in enumerate(bt["rounds"])}
    lines = [r"\begin{tabular}{lrrr}", r"\toprule",
             r"Round & Ensemble & User (actual) & Random baseline \\",
             r"\midrule"]
    for stage in ALL_STAGES:
        label = STAGE_LABEL[stage]
        if stage in have:
            i = have[stage]
            ens = bt["series"].get("ensemble", [])
            e = f"{ens[i]:.0f}" if i < len(ens) else "--"
            u = f"{bt['series']['user_actual'][i]:.0f}"
            rb = f"{bt['series']['random_baseline'][i]:.0f}"
            lines.append(f"{label} & {e} & {u} & {rb} " + r"\\")
        else:
            lines.append(f"{label} & " + " & ".join([r"\POSTFINAL{tbd}"] * 3)
                         + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    _write(out_dir, "tab_season_summary.tex", "\n".join(lines) + "\n")
    return []


def holdout_v4_macros() -> list[tuple[str, str]]:
    """Per-position holdout RMSE of the deployed v4xg GBM (separate file;
    data/training/validation_report.json stays the v2-era routing basis)."""
    import json
    path = ROOT / "data/training/validation_report_v4xg.json"
    if not path.exists():
        return []
    rows = json.loads(path.read_text())["position_rmse"]
    return [(f"Rmse{r['position'].title()}GbmVFour", _f(r["gbm_rmse"]))
            for r in rows]


def tab_forecaster_skill(out_dir: Path) -> list[tuple[str, str]]:
    """Component skill table for the match-forecast subsection."""
    import json
    path = ROOT / "data/evaluation/match_prediction_skill.json"
    if not path.exists():
        return []
    d = json.loads(path.read_text())
    s1, sa = d["skill_1x2"], d["skill_advance"]
    label = {"elo": "Elo", "dixon_coles": "Dixon--Coles",
             "xg_poisson": "xG-Poisson", "market": "Market (trophy ratio)"}
    lines = [r"\begin{tabular}{lrrrr}", r"\toprule",
             r"Component & 1X2 RPS & $n$ & Advance log-loss & $n$ \\",
             r"\midrule"]
    for key in ("elo", "dixon_coles", "xg_poisson", "market"):
        c1 = s1.get(key)
        ca = sa.get(key)
        r1 = _f(c1["rps"]) if c1 else "--"
        n1 = str(c1["n"]) if c1 else "--"
        ra = _f(ca["log_loss"]) if ca else "--"
        na = str(ca["n"]) if ca else "--"
        lines.append(f"{label[key]} & {r1} & {n1} & {ra} & {na} " + r"\\")
    uni = d["baselines"]["uniform_rps"]
    lines.append(r"\midrule")
    lines.append(f"Uniform baseline & {_f(uni)} & {s1['elo']['n']} & -- & -- "
                 + r"\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    _write(out_dir, "tab_forecaster_skill.tex", "\n".join(lines) + "\n")
    w = d["weights"]["pool_advance"]
    return [
        ("ForecastEloRps", _f(s1["elo"]["rps"])),
        ("ForecastDcRps", _f(s1["dixon_coles"]["rps"])),
        ("ForecastXgRps", _f(s1["xg_poisson"]["rps"])),
        ("ForecastUniformRps", _f(uni)),
        ("ForecastEloAdvLoss", _f(sa["elo"]["log_loss"])),
        ("ForecastMarketAdvLoss", _f(sa["market"]["log_loss"])),
        ("ForecastMarketWeight", _f(float(w["applied"]["market"]), 2)),
        ("ForecastMarketCap", _f(float(w["cap"]), 2)),
    ]


def computed_macros() -> list[tuple[str, str]]:
    """Runtime-computed corpus numbers (no-drift rule)."""
    import glob

    import pandas as pd
    total = 0
    for fp in sorted(glob.glob(str(ROOT / "data/training/fpl_player_gameweek_*.parquet"))):
        d = pd.read_parquet(fp, columns=["minutes"])
        total += int((d["minutes"] > 0).sum())
    feats = sorted(glob.glob(str(ROOT / "data/processed/features_*.parquet")))
    ncols = len(pd.read_parquet(feats[-1]).columns) if feats else 0
    return [("EplTrainingRows", f"{total:,}".replace(",", "{,}")),
            ("FeatureColumnCount", str(ncols))]


def numbers(out_dir: Path, macros: list[tuple[str, str]]) -> None:
    seen = set()
    lines = []
    for name, val in macros:
        if name in seen:
            continue
        seen.add(name)
        lines.append(rf"\newcommand{{\{_macro_name(name)}}}{{{val}}}")
    _write(out_dir, "numbers.tex", "\n".join(lines) + "\n")


def main() -> int:
    p = argparse.ArgumentParser(prog="paper_tables")
    p.add_argument("--out", type=Path, default=ROOT / "paper/generated")
    args = p.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    macros: list[tuple[str, str]] = []
    macros += tab_holdout_rmse(args.out)
    macros += tab_walkforward(args.out)
    macros += tab_backtest_rounds(args.out)
    macros += tab_gk_ab(args.out)
    macros += tab_market_negative(args.out)
    macros += tab_season_summary(args.out)
    macros += tab_forecaster_skill(args.out)
    macros += holdout_v4_macros()
    macros += computed_macros()
    macros += HISTORICAL_MACROS
    numbers(args.out, macros)
    return 0


if __name__ == "__main__":
    sys.exit(main())
